# Generated by Django 5.1.3 on 2025-03-05 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_familles_options_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.types'),
        ),
        migrations.AlterField(
            model_name='types',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='shop.categories'),
        ),
    ]
