# Generated by Django 5.1.3 on 2025-03-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_type_alter_types_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
