# Generated by Django 5.1.3 on 2025-01-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_shopper_username_alter_shopper_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopper',
            managers=[
            ],
        ),
    ]
